# Generated by Django 3.0.9 on 2020-10-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20201030_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postassessment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hello.School'),
        ),
    ]
