# Generated by Django 3.0.9 on 2020-10-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_schoollist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolList',
            new_name='Schools',
        ),
    ]
