# Generated by Django 3.0.9 on 2020-10-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20201030_1458'),
        ('hello', '0003_auto_20201030_2019'),
    ]

    operations = [
    ]
