# Generated by Django 3.0.9 on 2020-10-30 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_merge_20201030_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postassessment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hello.Schools'),
        ),
        migrations.AlterField(
            model_name='preassessment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hello.Schools'),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
